import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { AuthProvider } from "@/providers/auth";
import UserProvider from "@/contexts/UserContext";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "QuiLVacation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "flex flex-col justify-center items-center"
        )}
      >
        <AuthProvider>
          <UserProvider>
            <Header />
            {children}
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
